server:
 servlet:
  context-path: /examen02/api
spring:
 datasource:  
  url: jdbc:mysql://localhost/dbexamen02?useSSL=false&serverTimezone = GMT
  username: root
  password: 
  hikari:
   connectionTimeout: 30000
   idleTimeout: 60000
   maxLifetime: 60000
   maximumPoolSize: 15
 jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect = org.hibernate.dialect.MySQL5Dialect
logging:
  level:
    root: WARN   
jwt:
  password: miclave123
 

